In [1]:
import sys

# Añade el directorio principal al path de búsqueda para importar módulos desde esa ubicación
sys.path.insert(0, "..")

import pandas as pd
import polars as pl

from merge_by_lev.main import *

In [2]:
# Create two Pandas DataFrames with the same name in their columns
df1 = pd.DataFrame({"Name": ["John", "Alice", "Bob"], "Age": [25, 30, 35]})
df2 = pd.DataFrame({"Name": ["Sara", "Lyna", "Melissa"], "Age": [23, 19, 20]})

# Create the list of Pandas DataFrames
df_list = [df1, df2]
name_list = ["df1", "df2"]

# Apply the function
print("lev_dist : ", lev_dist(name_list[0], name_list[1]))
dfs, names, mtx = merge_by_similarity(df_list=df_list, col_list=name_list)

lev_dist :  1
Computing: [########################################] 2/2

In [3]:
print(len(dfs))

1

In [4]:
dfs[0].head(10)

shape: (6, 2)
┌─────┬─────────┐
│ Age ┆ Name    │
│ --- ┆ ---     │
│ i64 ┆ str     │
╞═════╪═════════╡
│ 25  ┆ John    │
│ 30  ┆ Alice   │
│ 35  ┆ Bob     │
│ 23  ┆ Sara    │
│ 19  ┆ Lyna    │
│ 20  ┆ Melissa │
└─────┴─────────┘

In [5]:
# Create the list of Polars DataFrames
df_list = [pl.from_pandas(df1), pl.from_pandas(df2)]
name_list = ["df1", "df2"]

# Apply the function
print("lev_dist : ", lev_dist(name_list[0], name_list[1]))
dfs, names, mtx = merge_by_similarity(df_list=df_list, col_list=name_list)

lev_dist :  1
Computing: [########################################] 2/2

In [6]:
dfs[0].head(10)

shape: (6, 2)
┌─────┬─────────┐
│ Age ┆ Name    │
│ --- ┆ ---     │
│ i64 ┆ str     │
╞═════╪═════════╡
│ 25  ┆ John    │
│ 30  ┆ Alice   │
│ 35  ┆ Bob     │
│ 23  ┆ Sara    │
│ 19  ┆ Lyna    │
│ 20  ┆ Melissa │
└─────┴─────────┘

In [7]:
# Testing QualityAssessment
from merge_by_lev.tools import QualityAssessment

data = {"Name": ["John", "Alice", "Bob"], "Age": [25, 30, 35]}
df_pandas = pd.DataFrame(data)
df_polars = pl.DataFrame(data)
table_name = "test_table"
handler = QualityAssessment([df_pandas, df_polars])
handler.get_report([table_name + "_1", table_name + "_2"])

,column name,data type,database name,# rows,# missing rows,# missing rows (percentage),unique values
0,Name,String,test_table_1,3,0,0.00%,3
1,Age,Int64,test_table_1,3,0,0.00%,3
2,Name,String,test_table_2,3,0,0.00%,3
3,Age,Int64,test_table_2,3,0,0.00%,3