In [7]:
import sys

# Añade el directorio principal al path de búsqueda para importar módulos desde esa ubicación
sys.path.insert(0, "..")

import pandas as pd
import polars as pl

from merge_by_lev.main import *

In [8]:
# Create two DataFrames with the same name in their columns
df1 = pd.DataFrame({"Name": ["John", "Alice", "Bob"], "Age": [25, 30, 35]})
df2 = pd.DataFrame({"Name": ["Sara", "Lyna", "Melissa"], "Age": [23, 19, 20]})

# Create the list of DataFrames
df_list = [df1, df2]
name_list = ["df1", "df2"]

# Apply the function
print("lev_dist : ", lev_dist(name_list[0], name_list[1]))
dfs, names, mtx = merge_by_similarity(df_list=df_list, col_list=name_list)

lev_dist :  1
Computing: [########################################] 2/2

In [9]:
print(len(dfs))

1

In [10]:
dfs[0].head(10)

shape: (6, 2)
┌─────────┬─────┐
│ Name    ┆ Age │
│ ---     ┆ --- │
│ str     ┆ i64 │
╞═════════╪═════╡
│ John    ┆ 25  │
│ Alice   ┆ 30  │
│ Bob     ┆ 35  │
│ Sara    ┆ 23  │
│ Lyna    ┆ 19  │
│ Melissa ┆ 20  │
└─────────┴─────┘

In [11]:
# Create the list of Polars DataFrames
df_list = [pl.from_pandas(df1), pl.from_pandas(df2)]
name_list = ["df1", "df2"]

# Apply the function
print("lev_dist : ", lev_dist(name_list[0], name_list[1]))
dfs, names, mtx = merge_by_similarity(df_list=df_list, col_list=name_list)

lev_dist :  1
Computing: [########################################] 2/2

In [12]:
dfs[0].head(10)

shape: (6, 2)
┌─────────┬─────┐
│ Name    ┆ Age │
│ ---     ┆ --- │
│ str     ┆ i64 │
╞═════════╪═════╡
│ John    ┆ 25  │
│ Alice   ┆ 30  │
│ Bob     ┆ 35  │
│ Sara    ┆ 23  │
│ Lyna    ┆ 19  │
│ Melissa ┆ 20  │
└─────────┴─────┘